### ISSUE TITLE
Deploy with --name not working properly

### ISSUE THREAD

**Issue by jlfsjunior** [rstudio/rsconnect-python#154]
Hi,

First of all, thanks a lot for the efforts in bringing python to RSC. We've just installed version 1.8.4 after a long time in 1.7, and I am happy to see how python friendly it is becoming... 😄 

Regarding the problem I am experiencing: I have added a server named `rsc`. When I tried to deploy a content (for example, the notebook in RSC example) using the name flag, I got the following error:

```bash
$ rsconnect deploy notebook --name rsc stock-report-jupyter.ipynb quandl-wiki-tsla.json.gz 
Checking arguments...                            [ERROR]
Error: You must specify only one of -n/--name or -s/--server, not both.
```

The same error does not appear when I pass the server flag instead, the notebook is deployed normally. 

I am on version 1.5.0.

Is this a known issue?

Thank you!

**Comment by mmarchetti** [comment]
Since you didn't specify `--server` on the command line, it's likely that it was set implicitly via the `CONNECT_SERVER` environment variable. If that's the case, unsetting it should help.

**Comment by jlfsjunior** [comment]
That makes a lot of sense, because if I don’t pass any flag, it deploys in another instance that I haven’t registered (but I have the env variables for).

Thanks for the quick reply! I am closing it...
