### ISSUE TITLE
Add Support for FastAPI

### ISSUE THREAD

**Issue by ZeroCool2u** [rstudio/rsconnect-python#159]
Can we add [FastAPI ](https://fastapi.tiangolo.com/)support in the same way that Flask is supported? We really don't use Flask, because FastAPI is so much easier, even compared to Flask-RESTX, etc, and converting all our API's over to an entire other framework really isn't an option. Obviously this limits the usefulness of R Studio Connect.

I'm not sure how R Studio Connect runs a Flask app under the hood, but running a FastAPI instance is almost identical to running a Flask instance with gunicorn, so maybe this is actually pretty easy? Here are two commands that are effectively equivalent for running FastAPI normally and running it with gunicorn.

Is this an option? This would be incredibly helpful. 

```bash
uvicorn main:app --host super_server.theolinnemann.com --port 8080
gunicorn main:app -b super_server.theolinnemann.com:8080 -k uvicorn.workers.UvicornWorker
```

**Comment by bjakubowskiVNSNY** [comment]
Just seconding that this would be incredibly helpful!

**Comment by hhoeflin** [comment]
Is this on the roadmap?

**Comment by edavidaja** [comment]
Check out the release notes for the [August 2021](https://docs.rstudio.com/connect/news/#rstudio-connect-2021080) edition.

**Comment by ZeroCool2u** [comment]
That's awesome! Does this require a server side update as well or is updating the client sufficient?

**Comment by kellobri** [comment]
You'll need to upgrade RStudio Connect as well: https://docs.rstudio.com/rsc/upgrade/

**Comment by ZeroCool2u** [comment]
Got it, thanks!

**Comment by hhoeflin** [comment]
Just for clarification - is this being run inside an asynchronous server?
Can you share which one you are using?

Thanks
