### ISSUE TITLE
pip freeze in a conda environment produces unusable requirements.txt

### ISSUE THREAD

**Issue by christierney** [rstudio/rsconnect-python#166]
For a conda client, pip freeze seems to generate a requirements.txt with local file references.

see https://rstudioide.zendesk.com/agent/tickets/55886

`pip list --format=freeze > requirements.txt` seems to do the right thing.

see also https://github.com/pypa/pip/pull/7612

**Comment by mmarchetti** [comment]
`pip list --format=freeze` helps a lot. There are sometimes package versions in conda environments that don't exist for pip, e.g. we saw `setuptools=49.6.0.post` which is not available on PyPI.

**Comment by ekungurov** [comment]
Also do we have any documentation on how to use conda_mode=True ?
