### ISSUE TITLE
rsconnect deploy * --exclude doesn't work as expected

### ISSUE THREAD

**Issue by datakid** [rstudio/rsconnect-python#189]
Hi, new and nervous. I don't think rsconnect's `--exclude` works as expected. I think the problem is at 

https://github.com/rstudio/rsconnect-python/blob/master/rsconnect/bundle.py#L355

```
def create_glob_set(directory, excludes):
    """
    Takes a list of glob strings and produces a GlobSet for path matching.
    **Note:** we don't use Python's glob support because it takes way too
    long to run when large file trees are involved in conjunction with the
    '**' pattern.
    :param directory: the directory the globs are relative to.
    :param excludes: the list of globs to expand.
    :return: a GlobSet ready for path matching.
    """
    work = []
    if excludes:
        for pattern in excludes:
            file_pattern = join(directory, pattern)
            # Special handling, if they gave us just a dir then "do the right thing".
            if isdir(file_pattern):
                file_pattern = join(file_pattern, "**/*")
            work.append(file_pattern)

    return GlobSet(work)

```

Here is a reproducible example - when using the quoted/globbed method, the only files excluded are those that are files, in the directory. All directories in that directory, and files in the directories below that directory, remain included.

As you can see, the output `manifest.exclude-no-quotes.json` is 20 lines long, about what you'd expect. 

The `manifest.no-exclude.json` with no excludes is three lines longer than the `manifest.exclude-with-quotes.json` and those lines belong to the one file in the top directory of a virtualenv, `pyenv.cfg`. 

```
$ mkdir myapp 
$ cd myapp/
$ python3 -m venv myvenv 
$ cd ../
$ rsconnect write-manifest dash myapp
$ mv myapp/manifest.json manifest.no-exclude.json 
$ rsconnect write-manifest dash --exclude "myvenv/*" myapp
$ mv myapp/manifest.json manifest.exclude-with-quotes.json
$ rsconnect write-manifest dash --exclude myvenv myapp
$ mv myapp/manifest.json manifest.exclude_no_quotes.json
$ wc -l manifest.*
20 manifest.exclude-no-quotes.json
2255 manifest.exclude-with-quotes.json
2258 manifest.no-exclude.json
$ diff manifest.no-exclude.json manifest.exclude-with-quotes.json
18c18
<       "checksum": "9a4c24c0d1103bd5fb3adaf16bf6a7a5"
---
>       "checksum": "9a2dd16373cbce65e4af5a96953bbed9"
2254,2256d2253
<     },
<     "myvenv/pyvenv.cfg": {
<       "checksum": "7d14b668b0d01bc0238262bcaa504df5"
```

This is an issue in particular because we encourage people to use the globs in the documentation as can be seen in the example:

```
rsconnect deploy dash --exclude "workfiles/*" dash-app/ data.csv
```

https://docs.rstudio.com/rsconnect-python/#including-extra-files_1

**Comment by mmarchetti** [comment]
Thank you for this issue. I think I see what is happening here, and which we need to address in the documentation.

rsconnect-python is using git-style globs where `DIR/*` refers to files in the directory, and `DIR/**` refers to all files and directories under `DIR`.

The difference between quoting and not quoting is in where the `*` is resolved.

`rsconnect deploy . --exclude 'dir/*'` passes `dir/*` to rsconnect-python, which interprets that to mean 'files in dir but not in a subdirectory'

`rsconnect deploy . --exclude dir/*` causes the shell to expand dir/* to dir/file, dir/subdir, etc. rsconnect-python then excludes both the files and subdirectories because they are each named on the command line.

Would these documentation changes address the issue?
* Explain the difference between `--exclude dir`, `--exclude 'dir/*'`, and `--exclude 'dir/**'`
* Recommend using `--exclude dir` because it is the simplest way to exclude an entire directory tree

**Comment by datakid** [comment]
Hi Michael, thanks for the update. You are correct, this is a documentation issue.

I presumed the code was wrong because the documentation shows an unlikely usage that leads to worst-case situations.

I don't think that the first option is necessary - I was thrown by the use of the quotes at all.  It's sufficiently uncommon usage that it's confusing, and to be honest, I can't imagine a situation where you would use it.

The three main use cases I have experienced would be:

- exclude one file (no quotes)
- exclude one directory and everything below it without exception (no quotes)
- exclude more than one of the above in some combination (comma-separated; no whitespace, list; or multiple `--exclude` calls)

If you know of a situation where quotes would be necessary, then you could add that as an "if ... then..." to the docs. 

Apart from that, I think it should just show `--exclude file` or `--exclude dir` and leave it at that.

**Comment by mmarchetti** [comment]
Fixed in documentation
