### ISSUE TITLE
meaningful deployment error not output by rsconnect-python

### ISSUE THREAD

**Issue by sagerb** [rstudio/rsconnect-python#224]
With Connect v 2021-12-0, rsconnect-python (v1.6.0) does not appear to recognize nor output the error returned from the server when a python bundle is being deployed, but the server does not have python enabled (Python.Enabled = true). The dashboard does appear to be capturing this, as re-activating the bundle on the server will display the error shown below:

![2022-02-09 at 11 43 AM](https://user-images.githubusercontent.com/17675905/153278180-9c9d1aa6-1821-4630-9c67-fa07d7798e73.jpg)

Instead, it just shows this error:
```
~/dev/connect-content > rsconnect deploy manifest --server https://dev-password-k8s.localtest.me --api-key c7achTdggWVGtr851azThcyYDwH5JRgf --new --title fastapitableau-simple --insecure ~/dev/connect-content/bundles/fastapitableau-simple/manifest.json
Checking arguments...                            [OK]
    Deploying /Users/billsager/dev/connect-content/bundles/fastapitableau-simple/manifest.json to server "https://dev-password-k8s.localtest.me"
Creating deployment bundle...                    [OK]
Uploading bundle...                              [OK]
Saving deployment data...                        [OK]

Deployment log:
Building FastAPI application...
Error: Task exited with status 1.
```

This problem is exposed through connect-content/bundler as well as w/ YETI.

**Comment by mmarchetti** [comment]
Yes, IIRC this same problem occurs when publishing R content that uses`reticulate`, if python is not enabled or a matching python version cannot be found. It seems that Connect only returns log lines that originate from the external runtime processes and not from the Connect server itself.
