### ISSUE TITLE
quarto deployment fails 

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-python#231]
rsconnect-python 1.7.1
Connect 2022.01.0-dev+1189

The following was performed with the example found here:
https://quarto.org/docs/get-started/hello/jupyter.html 

**Problem Statement:**
Deploying the attached quarto app results in an error.

**STR:**
Deploy the quarto app using `deploy manifest` method:
`rsconnect deploy manifest ./manifest.json -n dogfood  -v`

This results in:
```
Completed Python build against Python version: '3.8.1'
Task failed. Task exited with status 1.
```

I did not find any other errors in the deploy logs, server logs, nor in the app logs here:
https://rsc.radixu.com/connect/#/apps/d8077432-c706-426e-9204-eca247bc4e95/logs

**Additional Notes:**
The above is the result from using `"appmode": "quarto-static"` in my manifest.json.  However, if I change that to `"appmode": "jupyter-static"`, deployment succeeds:
https://rsc.radixu.com/connect/#/apps/7b92ec5f-dacd-4192-a1ff-59dc2e7a808f/access/5325

[quarto bundle](https://github.com/rstudio/rsconnect-python/files/8081715/quarto.zip)
[full deploy log](https://github.com/rstudio/rsconnect-python/files/8081729/deploy_log.txt)

**Comment by mmarchetti** [comment]
Since the file was a notebook (.ipynb) and not a .qmd, this seems like the expected behavior.
