### ISSUE TITLE
refactor: content subcommand outputs invalid json

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-python#255]
`bcwu-refactor` branch.

The output for the `rsconnect content search` command now includes a `Validating server...` line.  This invalidates the json output and would break implementations if someone is using the command and attempting to parse the json programmatically.

Actual Behavior:
```
>  rsconnect content search --title-contains "python-dash" -s ${CONNECT_SERVER} -k ${API_KEY}
Validating server... 	[OK]
[INFO] 2022-06-13T16:47:14-0400 Initializing ContentBuildStore for http://localhost:3939
[
  {
    "guid": "a371a4cb-202d-4804-9ed5-66fa4d82d0ee",
    "name": "pip_python3-manifest-python-dash",
    "title": "pip python3-manifest-python-dash",
    "description": "",
...
```

Expected (current `master` branch behavior):
```
>  rsconnect content search --title-contains "python-dash" -s ${CONNECT_SERVER} -k ${API_KEY}
[
  {
    "guid": "a371a4cb-202d-4804-9ed5-66fa4d82d0ee",
    "name": "pip_python3-manifest-python-dash",
    "title": "pip python3-manifest-python-dash",
    "description": "",
....
```

**Comment by bcwu** [comment]
this was fixed in [a734376](https://github.com/rstudio/rsconnect-python/pull/244/commits/a734376bb90d9821ae296772a41da21c0bc4f9f6)
