### ISSUE TITLE
write-manifest shiny creates a wrong appmode

### ISSUE THREAD

**Issue by kgartland-rstudio** [rstudio/rsconnect-python#276]
rsconnect version 1.10.0

when running the command `rsconnect write-manifest shiny` , we create a manifest with the appmode `python-shiny` which isn't recognized by Connect so these manifests cannot be deployed.  The appmode should be `shiny`.

When deploying the manifest created, we throw this error:

```
ValueError: No app mode named python-shiny
Internal error: No app mode named python-shiny
```

**Comment by mmarchetti** [comment]
`python-shiny` is the correct app mode for Connect - it looks like that error comes from rsconnect-python trying to validate the manifest before deploying.

**Comment by kgartland-rstudio** [comment]
user-error. sorry about that!
