### ISSUE TITLE
deploy task timeouts look like successful deploys

### ISSUE THREAD

**Issue by samperman** [rstudio/rsconnect-python#287]
If i trigger a deploy that takes more than 3 minutes the output looks like this:

```
❯ rsconnect deploy shiny my-shiny-app/ --name cloud-staging --title my-shiny-app
    Warning: the existing manifest.json file will not be used or considered.
Validating server... 	[OK]
Validating app mode... 	[OK]
Making bundle ... 	[OK]
Deploying bundle ...
Waiting for task: 2d8ebc8d-be16-4a85-abd5-143fd1350123
  started - name=build-output
  started - name=build-output
  
  .... snipped repeated lines ...
  
  started - name=build-output
Task done: name=build-output
Application successfully deployed to https://fcadf37e6dd74f4c9848d959986a9816.app.staging.rstudio.cloud/
 	[OK]
Saving deployed information... 	[OK]
```

The issue here is that this task was not finished, and the deploy was not done (it eventually failed) but my browser was opened to the application url (which failed) and the output looks like it work.

I suspect it is this code that ends the loop when the timeout is reached:

https://github.com/rstudio/rsconnect-python/blob/dee0e6a757f41c68fff79d46fa14bb2dddf267e7/rsconnect/api.py#L1075-L1095

**Comment by mslynch** [comment]
fixed in cloud-deploys branch with this commit: https://github.com/rstudio/rsconnect-python/commits/19509b59e913ba52544adb55e5f730795d2fa5ad

**Comment by samperman** [comment]
verified
