### ISSUE TITLE
Deploying quarto document with existing APP ID

### ISSUE THREAD

**Issue by TheisFerre** [rstudio/rsconnect-python#308]
Hi

I have a use-case, where I need to create/register an "empty" RStudio Connect content item before I do the actual deployment/rendering of my Quarto document. The reason being, is that I have a CI/CD pipeline, where I need to render the document with a different user than the one who creates the deployment. The desired deployment steps are something like this:

1. Check if content with specific name exists
2. If not, create an "empty" RStudio Connect content item calling the POST /v1/content API
3. Set the content item to run-as another user than the one publishing the content item
4. Deploy/render Quarto document to the (new) content item

Everything works as expected, but when I get to the fourth step, I can not deploy the Quarto document. The error that I get comes from the `validate_app_mode` function, in the `reconnect/api.py` file. Specifically it is this line in the function: 

```python
if existing_app_mode and app_mode != existing_app_mode:
```

that evaluates to `True`. 

It should be noted, that the existing_app_mode is "unknown", when the content item is created from the API mentioned in step 2 above. 

If I instead use the [R-rsconnect package](https://github.com/rstudio/rsconnect), I do not get this error as this package allows me to deploy a Quarto Document in an existing content item with `app_mode=unknown`.

I propose, that you add a check in the `validate_app_mode` function, such that it is allowed to deploy a quarto (or any other) document, to an existing content item that has `app_mode=unknown`. I could be as simple as the following:

```python
def validate_app_mode(self, *args, **kwargs):
        path = (
            self.get("path", **kwargs)
            or self.get("file", **kwargs)
            or self.get("file_name", **kwargs)
            or self.get("directory", **kwargs)
            or self.get("file_or_directory", **kwargs)
        )
        app_store = self.get("app_store", *args, **kwargs)
        if not app_store:
            module_file = fake_module_file_from_directory(path)
            self.state["app_store"] = app_store = AppStore(module_file)
        new = self.get("new", **kwargs)
        app_id = self.get("app_id", **kwargs)
        app_mode = self.get("app_mode", **kwargs)

        if new and app_id:
            raise RSConnectException("Specify either a new deploy or an app ID but not both.")

        existing_app_mode = None
        if not new:
            if app_id is None:
                # Possible redeployment - check for saved metadata.
                # Use the saved app information unless overridden by the user.
                app_id, existing_app_mode = app_store.resolve(self.remote_server.url, app_id, app_mode)
                logger.debug("Using app mode from app %s: %s" % (app_id, app_mode))
            elif app_id is not None:
                # Don't read app metadata if app-id is specified. Instead, we need
                # to get this from the remote.
                if isinstance(self.remote_server, RSConnectServer):
                    app = get_app_info(self.remote_server, app_id)
                    existing_app_mode = AppModes.get_by_ordinal(app.get("app_mode", 0), True)
                elif isinstance(self.remote_server, RStudioServer):
                    app = get_rstudio_app_info(self.remote_server, app_id)
                    existing_app_mode = AppModes.get_by_cloud_name(app.json_data["mode"])
                else:
                    raise RSConnectException("Unable to infer Connect client.")

            # add (existing_app_mode != "unknown") check, to allow deploying if app_mode is not set.
            if existing_app_mode and app_mode != existing_app_mode and existing_app_mode != "unknown":
                msg = (
                    "Deploying with mode '%s',\n"
                    + "but the existing deployment has mode '%s'.\n"
                    + "Use the --new option to create a new deployment of the desired type."
                ) % (app_mode.desc(), existing_app_mode.desc())
                raise RSConnectException(msg)

        self.state["app_id"] = app_id
        self.state["app_mode"] = app_mode
        return self
```

I will happily submit a PR if you agree that this is a good idea.

**Comment by bcwu** [comment]
Thank you for opening the issue and elaborating on your use-case. We opened a PR to incorporate your suggestion.
