### ISSUE TITLE
Deployment worked locally but failed on Google Colab

### ISSUE THREAD

**Issue by hellozeyu** [rstudio/rsconnect-python#372]
I have a simple app that I can deploy successfully on my local machine using Python 3.9.16, which is the current Python version on Google Colab. However, the same procedure failed on Colab and the error message didn't give me any information. I also noticed that it will create a separate app (my-app-colab vs my-app-colab1) if I ran the deploy code twice. Any thoughts?

Error message from Colab
```
[ERROR]: shinyapps.io reported an error (calling /v1/tasks/1282969185?legacy=true): Unhandled Exception: Child Task 1282969186 failed: Error building image: Build exited with non-zero status: 1
```

The first one was deployed on my local machine
![Screenshot 2023-03-17 at 8 26 52 PM](https://user-images.githubusercontent.com/7503804/226073163-3c0b8c80-6cce-49af-a9ee-7f02f96bfb50.png)

The simple example app.
```
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.input_numeric("x", "Number input", value=100),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        return f"x: {input.x()}"


app = App(app_ui, server, debug=True)
```

**Comment by hellozeyu** [comment]
Thank you! @mmarchetti It solved the problem. Does rsconnect have any verbose argument that can print out the detailed error message for us to debug?

**Comment by mmarchetti** [comment]
Detailed logging was added in https://github.com/rstudio/rsconnect-python/pull/453.
