### ISSUE TITLE
Write up migration plan for "requests" adoption.

### ISSUE THREAD

**Issue by tdstein** [rstudio/rsconnect-python#398]
Create a document describing why and how we can refactor the library to use the `requests` package.

https://pypi.org/project/requests/

**Comment by mmarchetti** [comment]
Also see https://github.com/rstudio/rsconnect-python/issues/400

**Comment by tdstein** [comment]
Here is my initial write-up detailing why migrating to Requests is advantageous: https://docs.google.com/document/d/1n8HlHO7VpPIV2oJxsMRCmtR-FxE2dZ_9VZ5FYzA4R7A/edit?usp=sharing
