### ISSUE TITLE
how to enable Connect server to accept Python API?

### ISSUE THREAD

**Issue by indapa** [rstudio/rsconnect-python#426]
Hi, 
I tried to deploy a streamlit app like so:

` rsconnect deploy streamlit   --server https://myserver.com --api-key XXXXX --entrypoint streamlit_app.py myApp`

And then got this error:
`Error: The Posit Connect server does not allow for Python APIs`

I am not really sure how to resolve this to enable my Connect server to accept python APIs. Can someone help point me in the right direction?

**Comment by mmarchetti** [comment]
Hi @indapa, the documentation at https://docs.posit.co/rsc/integration/python/ shows how you can configure Python in Posit Connect. If that doesn't help, you might consider opening a ticket with Posit Support.

**Comment by mmarchetti** [comment]
Closing since this is not an rsconnect-python issue.
