### ISSUE TITLE
Failure to deploy "Basic App" example: Error message could be improved.

### ISSUE THREAD

**Issue by jwalsh-fbs** [rstudio/rsconnect-python#432]
When attempting to deploy the example "Basic App" [found here](https://shinylive.io/py/examples/#basic-app), I get the following output, which doesn't give one much to go on to figure out the cause.

 Warning: Capturing the environment using 'pip freeze'.
             Consider creating a requirements.txt file instead.
Validating server...    [OK]
Validating app mode...  [OK]
Making bundle ...       [OK]
Deploying bundle ...
Waiting for task: 1307226511
  building - Processing bundle: 7311608
  building - Installing files
  building - Installing files
  building - Installing files
  building - Installing files
  building - Installing files
  building - Installing files
        [ERROR]: Application deployment failed with error: Unhandled Exception: Child Task 1307226512 failed: Error building image: Build exited with non-zero status: 1
Error: Application deployment failed with error: Unhandled Exception: Child Task 1307226512 failed: Error building image: Build exited with non-zero status: 1

**Comment by GShotwell** [comment]
James is on version 1.17.1 and deploying from Mac

**Comment by nealrichardson** [comment]
Happened to me too this morning: 

```
Validating server... 	[OK]
Validating app mode... 	[OK]
Making bundle ... 	[OK]
Deploying bundle ...
Waiting for task: 1314971171
  building - Processing bundle: 7414606
  building - Installing files
  building - Installing files
  building - Installing files
 	[ERROR]: Application deployment failed with error: Unhandled Exception: Child Task 1314971172 failed: Error building image: Build exited with non-zero status: 1
Error: Application deployment failed with error: Unhandled Exception: Child Task 1314971172 failed: Error building image: Build exited with non-zero status: 1
```

On shinyapps.io, the app shows up but has a status of "Undeployed"
<img width="1096" alt="Screenshot 2023-07-03 at 9 59 48 AM" src="https://github.com/rstudio/rsconnect-python/assets/2975928/82589487-ee4b-4a20-a49c-057ad4aabaf1">

Clicking the "Restart" button errors with "Unable to deploy application=9400992. No current image to deploy." There's no hints given anywhere about how to solve this, and https://docs.posit.co/shinyapps.io/Troubleshooting.html doesn't mention this failure mode.

I am also on macOS, `rsconnect-python==1.17.1`

**Comment by kippandrew** [comment]
I'm curious why the task logs were not returned on this deploy task failure. Does `reconnect-python` fetch the build logs when a deploy fails, similar to what happens in `rsconnect`?? cc @mslynch @omar-rs

**Comment by mslynch** [comment]
I think we just overlooked returning the task logs. I see no reason not to.

**Comment by mslynch** [comment]
> Re: logs, was this already reported as #427?

Yes.
