### ISSUE TITLE
Add Posit Cloud support to rsconnect deploy quarto

### ISSUE THREAD

**Issue by mslynch** [rstudio/rsconnect-python#436]
Posit Cloud is gaining support for server-rendered static content, including rendering with Quarto. We should triggering server-render deploys through `rsconnect deploy quarto` (as is supported for Connect).

**Comment by omar-rs** [comment]
Quarto manifests generated by `rsconnect-python` don't have the R version in them.  Bender fails on picking an R version currently, so this is blocked until bender is fixed.

https://github.com/rstudio/lucid-bender/issues/168

**Comment by omar-rs** [comment]
Also, quarto docs with python in them require jupyter, which the data science image needs to support: 
https://github.com/rstudio/lucid-images-ide/issues/223
