### ISSUE TITLE
Adjust the Default Timeout for Long-Lived Task

### ISSUE THREAD

**Issue by tdstein** [rstudio/rsconnect-python#442]
The existing default timeout is too low for build operations. Increase the build timeout substantially to allow for long-lived builds.

**Comment by nealrichardson** [comment]
Is this what happened in the report on the Shiny discord: https://discord.com/channels/1109483223987277844/1116055413960474756?

> I'm trying to deploy a Python Shiny app on the Connect server, but it errors out: Unable to connect to worker after 60 seconds; startup took too long." The last line of log reads "Downloading pytorch_model.bin: 0%| | 0.00/1.56G [00:00". Any tips on how to resolve this issue?

**Comment by tdstein** [comment]
@nealrichardson - I don't think so. Based on the information you provided, it appears that the user's application is stuck while attempting to download PyTorch during startup.

**Comment by mmarchetti** [comment]
That is controlled by the Init Timeout setting in Connect.

**Comment by tdstein** [comment]
Related to #445
