### ISSUE TITLE
Environment variable is not passed to Shiny app when deployed to ShinyApps.io using -E flag

### ISSUE THREAD

**Issue by Dan-C-Reed** [rstudio/rsconnect-python#531]
I have a Python Shiny app that looks like this:

```
from shiny import App, ui, render
import os

app_ui = ui.page_fluid(
    ui.output_text("my_text")
)

def server(input, output, session):
    @output
    @render.text
    def my_text():
        return os.environ['BOOP']
    
app = App(app_ui, server)
```

And I deploy it to ShinyApps.io like this:

```
rsconnect deploy shiny . --name myname --title your-app-name -E BOOP=test
```

The environment variable does not get printed as expected. Now, say I specify it in my local environment before deployment:

```
export BOOP=test
echo $BOOP
# test
```
And try ,

```
rsconnect deploy shiny . --name myname --title your-app-name -E BOOP
```
This also does not work. 

To ensure that my code can in fact access environment variables, I modified my app to access the `PATH` environment variable rather than `BOOP` (because I _know_ that exists on the server without me having to set it) and I can see that variable just fine, so the issue doesn't seem to be my code accessing environment variables, but rather the variable getting passed using `rsconnect`.

Why can I not pass an environment variable using the flag described in the `reconnect deploy shiny` documentation? Is it an error in my approach or is this not possible using `rsconnect` for ShinyApps.io?

**Comment by aronatkins** [comment]
This is also related to #439, as shinyapps.io does not offer environment variable support.

**Comment by Dan-C-Reed** [comment]
I missed that – thanks for the heads up, @aronatkins.

(For others who stumble upon this, #437 already raised this issue.)
