### ISSUE TITLE
deploy dash - Unable to specify nested entry point 

### ISSUE THREAD

**Issue by HenrikSpiegel** [rstudio/rsconnect-python#550]
I have the following project structure:

```
├── app
│   ├── __init__.py
│   ├── __pycache__
│   ├── assets
│   ├── datareview_app.py
│   ├── pages
├── datareview
│   ├── __init__.py
│   ├── datareview.py
│   ├── (...)

├── inst
│   └── data
├── requirements.txt
```

I run the deployment using:
```
rsconnect deploy dash \
    --server XXX \
    --api-key  XXX \
    --insecure \
    --entrypoint app/datareview_app.py \
    .
```

and get the following error:
```
2024/03/18 12:24:54 PM: Error while loading Python API: Could not import module 'app/datareview_app'. Connect expected to find a file in the application directory named 'app/datareview_app.py'. Please check the entrypoint specified in the manifest.json file or on the rsconnect-python command line. Reason: No module named 'app/index'.
```

I have a 1:1 setup on a different project but using streamlit instead of dash and have no issues there.

**Comment by mmarchetti** [comment]
Flask, Dash, etc. expect the entrypoint to be in module:object format [as described in the Flask documentation](https://flask.palletsprojects.com/en/2.3.x/cli/#application-discovery). It should work with `--entrypoint app.datareview_app` as long as the application object within the python file has one of the standard names (e.g. `app`); if not, you can use `--entrypoint app.datareview_app:myapp` or similar.

**Comment by HenrikSpiegel** [comment]
Perfect thank you so much - I had simply misunderstood the documentation.
