### ISSUE TITLE
Deploy api uses entrypoint from manifest even if --entrypoint is specified

### ISSUE THREAD

**Issue by mmarchetti** [rstudio/rsconnect-python#76]
If there's an existing manifest.json, and you `rsconnect deploy api --entrypoint module:object`, it will use the entrypoint in the manifest.

It seems like either:
* the specified `--entrypoint` value should take effect, or
* the specification of `--entrypoint` on the command line should be an error

**Comment by jskress** [comment]
This will be tracked in https://github.com/rstudio/connect/issues/16793
