### ISSUE TITLE
There is no `details` command

### ISSUE THREAD

**Issue by jeffkeller87** [rstudio/rsconnect-python#84]
The [README mentions a `details` command](https://github.com/rstudio/rsconnect-python#verifying-server-information) for verifying the details of an RStudio Connect instance, but this command does not exist.

```
ubuntu@run-5e67933ffe37f60006125b99-qj4t5:/mnt$ rsconnect version
1.3.0
ubuntu@run-5e67933ffe37f60006125b99-qj4t5:/mnt$ rsconnect --help
Usage: rsconnect [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  add             Add a server
  deploy          Deploy content to RStudio Connect
  info            Show saved information about the specified deployment
  list            List saved servers
  remove          Remove a server
  test            Verify a Connect server URL
  version         Show the version of rsconnect-python
  write-manifest  Create a manifest.json file for later deployment from git
```

**Comment by jskress** [comment]
You must have gone the `pip install` route.  That installs version 1.3.0 of this library which does not have the `details` command.  The `README` has been updated in preparation for the next release which is nearly done.  If you want to play with the newer stuff, go the clone repo/python setup.py route.  Just know we don't have all the bugs squashed yet but this week is for doing that.

**Comment by jeffkeller87** [comment]
That is exactly what I did! Thanks for the background info.
